# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-API-Hooks
version:      1.0443
version_from: lib/POE/API/Hooks.pm
installdirs:  site
requires:
    Params::Validate:              0
    POE:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
