---
author:
  - 'Matt Cashner (sungo@pobox.com)'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Distribution: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.82'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-API-Hooks
no_index:
  directory:
    - inc
    - t
requires:
  POE: 1.0001
  Params::Validate: 0
  Test::More: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 1.08
